### ISSUE TITLE
fixing the usage of UT core functions 

### ISSUE THREAD

**Issue by hari22yuva** [rdkcentral/rdk-halif-test-hdmi_cec#1]
In order to support V2 of the ut-core, the following changes need to take place to the current testing code

- Upgrade trigger scripts to support V2 of the testing suites
- V2 introduces fall through for the UT_ASSERT macros, so verify that all the tests are correctly operating with the fall through model.

**Comment by Ulrond** [comment]
can you extend the description in this ticket please , so it's clear what you mean by the title, and correct the title.

**Comment by hari22yuva** [comment]
> can you extend the description in this ticket please , so it's clear what you mean by the title, and correct the title.

updated the description

**Comment by Ulrond** [comment]
@hari22yuva  is this still active?
