### ISSUE TITLE
EMU: Initial Startup, state machine and build makery

### ISSUE THREAD

**Issue by sramani-metro** [rdkcentral/rdk-halif-test-hdmi_cec#15]
## Goal: Create Intiial Startup and basic code to build.

- Defining data structures to hold statement machine
- Emulator header file definitions for init / de-init
- Driver code to startup requirements
- Load configuration, read variables, create the initial state of the drivers.

## Init/Deinit

- Load values from Profile config
  - KVP
- Makery - Build/Install
 - Setup State machine
 - Local data structures
- Build device network topology
- Threading for callbacks
- Auto allocate logical addresses

## Acceptance Criteria

- Builds basic emulator
- Basic code to initialise the emulator with the basic configuration of a TV
- Verify that the statement reflects that configuration.

**Comment by Ulrond** [comment]
- Ticket descriptions should clearly and concisely describe the problem to be solved and the desired outcome.
- Sub-tickets should only be created for actions that are necessary to achieve the desired outcome of the parent ticket.
- Acceptance criteria should be defined for each ticket to ensure that the work is completed correctly.

**Comment by sramani-metro** [comment]
1. Created Emulator start/stop tests with ut_core.
2. Enhanced test main to pass in profile path and control plane parameters
3. Created a few test profile yaml configs under emulator/profiles/ for testing. Started testing with sink (TV) config

  To build:
   #./build_ut.sh 
  This will now build emulator sources instead of the skeleton sources.

  To Run:
  #./ut/bin/run.sh -p <AbsolutePath>/rdk-halif-hdmi_cec/ut/emulator/profiles/test_sink.yaml -c 9998

After running, select the Emulator Lifecycle menu to start the emulator.

**Comment by sramani-metro** [comment]
Created PR https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/pull/21

**Comment by sramani-metro** [comment]
## Whats done
Addressed majority of the review comments.
Renamed emulator as Virtual Component.
All methods now handle negative cases first and then the positive flow.
Updated the template to configure the device map as a N-ary tree. this will allow the device network to be represented in the yaml config as a parent/children relationship. Provided Insert/Remove/Find functionality to manage devices in the network.
Made the L1 tests pass based on the updated changes

## Whats next
Waiting for inputs on moving enum strings mapping functionality to ut_kvp as a generic function.

**Comment by Ulrond** [comment]
Moved to closed due to #21 being resolved - new branch required for new work.
