### ISSUE TITLE
Documnetation: Define list of CEC Messages Possible For Sink / Source

### ISSUE THREAD

**Issue by sramani-metro** [rdkcentral/rdk-halif-test-hdmi_cec#17]
## Goal: Set requirements for messages to support, 

- Define a list of messages that we require to support
- List out all messages possible, and define a table of possible messages / implemented as part of the support documentation.

### Examples

User Commands
-Active Source Request
-Add/Remove devices
-Catalogue of Commands
-Dynamic base config change

## Acceptance Criteria

- Created support for the messages required to implement (covering main areas).
- Documentation is in place to allow users to understand supported features
- Test to support main features needs to exist.

**Comment by Ulrond** [comment]
* Trigger all the classic comments in the real world
* Document automatically triggered devices compared to external stimulas messages.

**Comment by Ulrond** [comment]
### Next Steps

* Trigger all the classic comments in the real world
* Document automatically triggered messages compared to externally stimulated messages.
* Generating the lists from resources on the internet, the spec.
* Cross reference with the capabilities of the main rdk source code, if possible
* In a real world setup, what messages are likely to be triggered
* We can discuss with the UI Team if require on messages they expect.
* Review with architecture
