### ISSUE TITLE
EMU: Use the control plane to trigger CEC commands

### ISSUE THREAD

**Issue by sramani-metro** [rdkcentral/rdk-halif-test-hdmi_cec#18]
## Goal: Integrate with the control plane

- Trigger Active source (One touch play)
- Hot plug

Blocked By [UT_Control Plane - Control message system for running component](https://github.com/rdkcentral/ut-core/issues/20)

## Acceptance Criteria

- Messages can be sent through the control plane via curl
- emulator test receives callback to support change of active source
- emulator test receives a callback to support hotplug of device.

**Comment by Ulrond** [comment]
you want to create a PR for this so we can get it merged?

**Comment by sramani-metro** [comment]
> you want to create a PR for this so we can get it merged?

Created https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/pull/37

**Comment by Ulrond** [comment]
Resolved as part of Demo Milestone
