### ISSUE TITLE
CEC L1 Test case changes based on L2 Interface Update

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-test-hdmi_cec#22]
There are few changes that needs to be done on HDMI CEC L1 due to the recent change in interface file during L2.

1. Remove all the CECTxAsync references for both source and sink devices. 
2. Physical address check should be done with F.F.F.F and not with 4.4.4.4
3. There are few test cases for source device which looks to add and remove logical address.  Now as the interface files clearly says that source devices has to return NOT_SUPPORTED, these test cases needs to be changed.

**Comment by srinivasgtl** [comment]
@krishna-1809 , all changes concerning the latest interface file are now addressed in PR #36.  Please check if it satisfies all the above requirements.  If yes, we can close this issue.

**Comment by krishna-1809** [comment]
@srinivasgtl , PR #36 has the above changes. Hence closing this issue
