### ISSUE TITLE
L1 VTS - Improve L1 based on new header File Updates (1.3.9)

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-hdmi_cec#36]
This task is to consider the latest header file updates and consider if there are any changes in L1 concerning the newest header files.

**Comment by akhilbhas** [comment]
Issue resolved through the pull request https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/pull/38

**Comment by srinivasgtl** [comment]
all changes are now available in tag 1.3.0
