### ISSUE TITLE
Creating a HDMI CEC Test pack.

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-hdmi_cec#4]
Create a HDMI CEC Test pack that covers L2, L3

**Comment by Ulrond** [comment]
Removed Testing Done -> That's not valid... If this is a testing ticket and theres work to be done, then do the work, report on the ticket, and close the ticket..

It's not a State of either a code change, or something thats in remove, the state is being removed.

**Comment by srinivasgtl** [comment]
these docs are now merged with issue 24 along with source device hdmi cec documentation and then pushed to develop

**Comment by Ulrond** [comment]
Closed due to PR #28 and to issue #24
