### ISSUE TITLE
vComponent: Add Remove Device Support

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/rdk-halif-test-hdmi_cec#41]
### Description:

**Problem/Opportunity:** 

- Adding support to the vDevice to add and remove a node from the network via the control plane. 
	- Add a new device, nothing the application knows about
	- When we write an L3 test for this, we need to trigger some command, from the newly added device

**Proposed Solution:**

- When a new device is added to the network, the device broadcasts its physical address to all devices through the ReportPhysicalAddress command. This can be used to validate the AddDevice command from control plane.
- Update the validation profile to add ReportPhysicalAddress with appropriate parameters

### Acceptance Criteria  (Optional):

* Trigger an L3 test which waits for ReportPhysicalAddress to be received through receive callback.
* Using control plane, trigger AddDevice command as per the design document.
* This should add a new device to the bus and automatically ReportPhysicalAddress is triggered in the driver callback.
* L3 test to verify the Receive callback payload with validation data.

### Additional Notes (Optional):

* To test RemoveDevice, 
      * trigger any L3 test other than AddDevice. 
      * Using control plane, trigger AddDevice command
      * Using control plane, trigger PrintStatus command. This should list the device map with the added device
      * Using control plane, trigger RemoveDevice command. 
      * Using control plane, trigger PrintStatus command. This should list the device map with the device removed.

**Comment by Ulrond** [comment]
@sramani-metro  -> will this be on the roadmap or did you manage t have a look at this?

**Comment by sramani-metro** [comment]
@Ulrond This is already in review with https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/pull/46

**Comment by Ulrond** [comment]
no futher actions on this merged with #46
