### ISSUE TITLE
VTS L1,L2 - SoC Vendor Issue fix - HDMICEC

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-hdmi_cec#58]
Issues reported during Testing of HAL form Mediatek.

1) L1 : removeLogicalAddress_negative:
 - Update the wrong Error code used for comparison

2) L2: L2_TransmitCECCommand_Sink:
 - Update the Logical address used.

**Comment by hari22yuva** [comment]
merged to develop
