### ISSUE TITLE
L1 HdmiCecTx Test issue fix

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-hdmi_cec#61]
### Goals ###
Handling he broadcast bit ACT and NO_ACT  correctly during the Tx HAL API Test. (Refer CEC 6.1.2 section of HDMI Spec 1.4

### Updates ###
* Updating destination logic address in HdmiCecTx_positive test (from broadcast to a valid logical address)
* Updating Message buffer loading to reflect the change in destination address.

**Comment by hari22yuva** [comment]
merged to develop
