### ISSUE TITLE
EMU: load a configuration file and build device network topology

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/rdk-halif-test-hdmi_cec#9]
## Goal: Build network of devices based on configuration

- load a configuration file start the module
- Build network of devices based on configuration

## Acceptance Criteria

- The network of devices is up and running
- Tests created using ut-core to support the emulator functions

**Comment by sramani-metro** [comment]
## Tasks Completed
 Modified the devices data structure to linked list to cater for device addition/removal dynamically.
 Loaded links representing endpoints and connections from YAML config.
 
## Next steps
 Add Physical and logical address auto allocation logic

**Comment by sramani-metro** [comment]
## Tasks Completed
Updated the Yaml template to represent the device network as a N-ary tree with a parent/children relation ship between devices. 

## Next steps
Create an auto allocate function which traverses through the device N-ary tree and assigns the physical and logical addresses based on its connections. Needs GH #15 merged.

**Comment by Ulrond** [comment]
@sramani-metro  need to update your eta end dates and estimates etc..

**Comment by sramani-metro** [comment]
## Tasks Completed
Added physical and logical address auto allocation logic based on the new n-ary tree based device map.

##Next steps
Take up suggestions during code review of #15 like split up of files, moving profiles outside of the vcomponent directory etc

**Comment by sramani-metro** [comment]
PR created
